services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_counsellor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: gursimar17/ai-counsellor-backend:latest
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=postgresql://postgres:password@db:5432/ai_counsellor
    depends_on:
      - db

  frontend:
    image: gursimar17/ai-counsellor-frontend:latest
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000  # For local testing; replace with your EC2 IP for cloud deployment
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: